# Generated by Django 3.2.20 on 2023-07-25 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.BooleanField(default=False)),
                ('reserved_by', models.CharField(max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('age', models.IntegerField(default=16)),
                ('num_of_guests', models.IntegerField(default=1)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.gig')),
            ],
        ),
    ]
