# Generated by Django 3.2.20 on 2023-07-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
