# Generated by Django 3.2.20 on 2023-07-25 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('num_tickets', models.PositiveIntegerField()),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.gig')),
            ],
        ),
    ]
