# Generated by Django 3.2.20 on 2023-07-25 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20230725_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='ticket_sales',
            new_name='bookings',
        ),
    ]
